app:
  name: "web_app"
  mod: "dev"
  port: 8083
  start_time: "2022-04-15"
  machine_id: 3
  
log:
  level: "debug"
  filename: "visualize_signal.log"
  max_size: 200
  max_age: 30
  max_backups: 7

rabbitmq:
  user: "guest"
  pwd: "guest"
  ipv4_addr: "127.0.0.1"
  port: "5672"
  content-type: "application/json"
  exchanger: "signal"
  result_queue: "analyze_to_visualize"


signal:
  min: 1
  max: 1000

analyze:
  size: 100

visual:
  segments: 10